version: 2.1

jobs:
  pytest:
    parameters:
      cluster_type:
        type: string
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    environment:
      CLUSTER_TYPE: << parameters.cluster_type >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            sudo apt-get update
            sudo apt-get install -y mariadb-client-core-10.3 python3 python3-virtualenv
            virtualenv .env3 -p /usr/bin/python3
            source .env3/bin/activate
            pip install .
            pip install pytest pytest-dbt-adapter
      - run:
          name: Start SingleStore cluster and run integration tests
          command: |
            source .env3/bin/activate
            source ./.circleci/setup-cluster.sh start $CLUSTER_TYPE
            export S2_PASSWORD=$ROOT_PASSWORD  # project UI env-var reference
            pytest test/singlestore.dbtspec --no-drop-schema
            ./.circleci/setup-cluster.sh terminate $CLUSTER_TYPE

workflows:
  test:
    jobs:
      - pytest:
          name: "Managed Service connection test"
          matrix:
            parameters:
              cluster_type: 
                - s2ms
      - pytest:
          name: "SingleStore 7.5 connection test"
          matrix:
            parameters:
              cluster_type: 
                - ciab
